Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Areas/Admin/Models/BrandViewModels/BrandViewModel.cs
using MKaymaz_ECommerce.Common.Enums;
using MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.ProductViewModels;
using System;
using System.Collections.Generic;

namespace MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.BrandViewModels
{
    public class BrandViewModel
    {
        public BrandViewModel()
        {
            Products=new HashSet<ProductViewModel>();
        }
        public Guid Id { get; set; }
        public Status Status { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public int SortOrder { get; set; }
        public string DistributorCode { get; set; }
        public string Distributor { get; set; }
        public string ImageFile { get; set; }
        public string ShowcaseContent { get; set; }
        public string DisplayShowcaseContent { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string CanonicalUrl { get; set; }
        public string PageTitle { get; set; }
        public string Attachment { get; set; }
        public DateTime? CreatedDate { get; set; }

        public ICollection<ProductViewModel> Products { get; set; }
    }
}

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Areas/Admin/Controllers/BrandController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MKaymaz_ECommerce.Common.Dtos.Brand;
using MKaymaz_ECommerce.Web.UI.APIs;
using MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.BrandViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MKaymaz_ECommerce.Web.UI.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
    public class BrandController : Controller
    {

        private readonly IBrandApi _brandApi;
        private readonly IMapper _mapper;

        public BrandController(
            IBrandApi brandApi,
            IMapper mapper)
        {
            _brandApi = brandApi;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (User.Claims.FirstOrDefault(x => x.Type == "IsAdmin")?.Value != "True")
                return Redirect("/Home/Index");
            List<BrandViewModel> list = new List<BrandViewModel>();
            var listResult = await _brandApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<BrandViewModel>>(listResult.Content.ResultData);
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> Insert()
        {
            if (User.Claims.FirstOrDefault(x => x.Type == "IsAdmin")?.Value != "True")
                return Redirect("/Home/Index");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Insert(CreateBrandViewModel item)
        {
            if (ModelState.IsValid)
            {
                var insertResult = await _brandApi.Post(_mapper.Map<BrandRequestDto>(item));
                if (insertResult.IsSuccessStatusCode &&
                    insertResult.Content.IsSuccess &&
                    insertResult?.Content?.ResultData != null)
                    return RedirectToAction("Index");
                else
                    TempData["Message"] = "Kayıt işlemi sırasında bir hata oluştu!... Lütfen alanları kontrol edip tekrar deneyinzi...";
            }
            TempData["Message"] = "İşlem başarısız oldu!... Lütfen alanları kontrol edip tekrar deneyinzi...";
            return View(item);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            if (User.Claims.FirstOrDefault(x => x.Type == "IsAdmin")?.Value != "True")
                return Redirect("/Home/Index");
            UpdateBrandViewModel model = new UpdateBrandViewModel();
            var updateResult = await _brandApi.Get(id);
            if (updateResult.IsSuccessStatusCode && updateResult.Content.IsSuccess && updateResult.Content.ResultData != null)
                model = _mapper.Map<UpdateBrandViewModel>(updateResult.Content.ResultData);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateBrandViewModel item)
        {
            if (ModelState.IsValid)
            {
                var updateResult = await _brandApi.Put(item.Id, _mapper.Map<BrandRequestDto>(item));
                if (updateResult.IsSuccessStatusCode &&
                    updateResult.Content.IsSuccess &&
                    updateResult?.Content?.ResultData != null)
                    return RedirectToAction("Index");
                else
                    TempData["Message"] = "Güncelleme sırasında bir hata oluştu!... Lütfen alanları kontrol edip tekrar deneyinzi...";
            }
            TempData["Message"] = "İşlem başarısız oldu!... Lütfen alanları kontrol edip tekrar deneyinzi...";
            return View(item);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var deleteResult = await _brandApi.Delete(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Activate(Guid id)
        {
            var activateResult = await _brandApi.Activate(id);
            return RedirectToAction("Index");
        }
    }
}

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace MKaymaz_ECommerce.Web.UI.Areas.Admin.Controllers
{
    [Area("Admin"),Authorize]
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            if (User.Claims.FirstOrDefault(x => x.Type == "IsAdmin")?.Value != "True")
                return Redirect("/Home/Index");
            return View();
        }
    }
}

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MKaymaz_ECommerce.Common.Dtos.Product;
using MKaymaz_ECommerce.Web.UI.APIs;
using MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.ProductImageViewModels;
using MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.ProductViewModels;
using MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.UserViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MKaymaz_ECommerce.Web.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductApi _productApi;
        private readonly IUserApi _userApi;
        private readonly IMapper _mapper;
        private readonly IProductImageApi _productImageApi;

        public HomeController(
            IUserApi userApi,
            IMapper mapper,
            IProductApi productApi, IProductImageApi productImageApi)
        {
            _userApi = userApi;
            _mapper = mapper;
            _productApi=productApi;
            _productImageApi=productImageApi;
        }

        public async Task<IActionResult> Index()
        {
            List<ProductViewModel> list = new List<ProductViewModel>();
            var listResult = await _productApi.GetActive();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
            {
                List<ProductResponseDto> listData = listResult.Content.ResultData
                    .OrderByDescending(x => x.ViewCount)    
                    .Take(12)
                    .ToList();
                list = _mapper.Map<List<ProductViewModel>>(listData);
            }
            return View(list);
        }

        public async Task<IActionResult> Posts(Guid id)
        {
            List<ProductViewModel> list = new List<ProductViewModel>();
            var listResult = await _productApi.GetByCategoryId(id);
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductViewModel>>(listResult.Content.ResultData);
            return View(list);
        }

        public async Task<IActionResult> Brands(Guid id)
        {
            List<ProductViewModel> list = new List<ProductViewModel>();
            var listResult = await _productApi.GetByBrandId(id);
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductViewModel>>(listResult.Content.ResultData);
            return View(list);
        }

        public async Task<IActionResult> Post(Guid id)
        {
            var getProductResult = await _productApi.ProductDetail(id);
            if (getProductResult.IsSuccessStatusCode && getProductResult.Content.IsSuccess && getProductResult.Content.ResultData != null)
            {
                ProductViewModel updateProduct = _mapper.Map<ProductViewModel>(getProductResult.Content.ResultData);
                var getUserResult = await _userApi.Get(updateProduct.UserId);
                if (getUserResult.IsSuccessStatusCode && getUserResult.Content.IsSuccess && getUserResult.Content.ResultData != null)
                {
                    UserViewModel userViewModel = _mapper.Map<UserViewModel>(getUserResult.Content.ResultData);
                    return View(updateProduct);
                }
            }
            return View();

        }

        public async Task<IActionResult> PostsProductImage(Guid id)
        {
            List<ProductImageViewModel> list = new List<ProductImageViewModel>();
            var listResult = await _productImageApi.GetByProductId(id);
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductImageViewModel>>(listResult.Content.ResultData);
            return View(list);
        }
    }
}
 

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/ViewComponents/BrandViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MKaymaz_ECommerce.Web.UI.APIs;
using MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.BrandViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MKaymaz_ECommerce.Web.UI.ViewComponents
{
    public class BrandViewComponent:ViewComponent
    {
        private readonly IBrandApi _brandApi;
        private readonly IMapper _mapper;

        public BrandViewComponent(IMapper mapper, IBrandApi brandApi)
        {
            _mapper = mapper;
            _brandApi=brandApi;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<BrandViewModel> list = new List<BrandViewModel>();
            var listResult = await _brandApi.GetActive();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<BrandViewModel>>(listResult.Content.ResultData);

            return View(list);
        }
    }
}

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/ViewComponents/CategoryViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MKaymaz_ECommerce.Web.UI.APIs;
using MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.CategoryViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MKaymaz_ECommerce.Web.UI.ViewComponents
{
    public class CategoryViewComponent : ViewComponent
    {
        private readonly ICategoryApi _categoryApi;
        private readonly IMapper _mapper;

        public CategoryViewComponent(ICategoryApi categoryApi, IMapper mapper)
        {
            _categoryApi = categoryApi;
            _mapper = mapper;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<CategoryViewModel> list = new List<CategoryViewModel>();
            var listResult = await _categoryApi.GetActive();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<CategoryViewModel>>(listResult.Content.ResultData);

            return View(list);
        }
    }
}

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Views/Home/Brands.cshtml
@model List<ProductViewModel>
@{
    ViewData["Title"] = "Posts";
}

@foreach (ProductViewModel item in Model)
{
    <div class="col-6 col-sm-6 col-md-4 col-lg-3 item">
        <!-- start product image -->
    <div class="product-image">
            <!-- start product image -->
         <a asp-controller="Home" asp-action="Post" asp-route-id="@item.Id">
                <!-- image -->
            <img class="primary blur-up ls-is-cached lazyloaded" data-src="@item.Barcode" src="@item.Barcode" alt="image" title="product">
                <!-- End image -->
             
        </a>
            <!-- end product image -->
            <!-- Start product button -->
       <form class="variants add"  asp-controller="Cart" asp-action="Post" method="post">
                <input asp-for="@item.Id" class="form-control" type="text" hidden />
                <button class="btn btn-addto-cart" type="submit" title="">Add Cart</button>
            </form>
            <div class="button-set">
                <a href="javascript:void(0)" title="Quick View" class="quick-view-popup quick-view" data-toggle="modal" data-target="#content_quickview">
                    <i class="icon anm anm-search-plus-r"></i>
                </a>
            </div>
            <!-- end product button -->
    </div>
        <!-- end product image -->
        <!--start product details -->
    <div class="product-details text-center">
            <!-- product name -->
        <div class="product-name">
                <a href="#">@item.FullName</a>
            </div>
            <!-- End product name -->
            <!-- product price -->
        <div class="product-price">
                <h3 >@item.Price1</h3>
            </div>
            <!-- End product price -->
    </div>
        <!-- End product details -->

</div>
}

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Views/Home/Index.cshtml
@model List<ProductViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-12 col-sm-12 col-md-3 col-lg-3 sidebar filterbar">
    <div class="closeFilter d-block d-md-none d-lg-none"><i class="icon icon anm anm-times-l"></i></div>
    <div class="sidebar_tags">
        <!--Categories-->
        <div class="sidebar_widget categories filter-widget">
            <div class="widget-content">
                <ul class="sidebar_categories">
                    <vc:category></vc:category>
                </ul>
            </div>
        </div>
        <!--Categories-->
        <!--Brand-->
        <div class="sidebar_widget filterBox filter-widget">
            <vc:brand></vc:brand>
        </div>
        <!--End Brand-->
    </div>
</div>
@foreach (ProductViewModel item in Model)
{
    <div class="col-6 col-sm-6 col-md-4 col-lg-3 item">
        <!-- start product image -->
        <div class="product-image">
            <!-- start product image -->
            <a asp-controller="Home" asp-action="Post" asp-route-id="@item.Id">
                <!-- image -->
                <img class="primary blur-up ls-is-cached lazyloaded" data-src="@item.Barcode" src="@item.Barcode" alt="image" title="product">
                <!-- End image -->
            </a>
            <!-- end product image -->
            <!-- Start product button -->
            <form class="variants add" asp-controller="Cart" asp-action="Post" method="post">
                <input asp-for="@item.Id" class="form-control" type="text" hidden />
                <button class="btn btn-addto-cart" type="submit" title="">Add Cart</button>
            </form>
           
            <!-- end product button -->
        </div>

        <!-- end product image -->
        <!--start product details -->
        <div class="product-details text-center">
            <!-- product name -->
            <div class="product-name">
                <a href="#">@item.FullName</a>
            </div>
            <!-- End product name -->
            <!-- product price -->
            <div class="product-price">
                <h3>@item.Price1</h3>
            </div>
            <!-- End product price -->
            <!-- Variant -->
            <!-- End Variant -->
        </div>
        <!-- End product details -->

    </div>

}

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Views/Home/Post.cshtml
@model ProductViewModel

@{
    ViewData["Title"] = "Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 col-12">
        <div class="product-details-img">
            <div class="pl-20">
                <img src="@Model.Barcode" alt="">
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-12">
        <div class="product-single__meta">
            <h2 class="product-single__title">@Model.FullName</h2>
            <div class="prInfoRow">
                <div class="product-stock"> <span class="instock ">In Stock</span> <span class="outstock hide">Unavailable</span> </div>
                <div class="product-sku">SKU: <span class="variant-sku">@Model.Sku</span></div>
            </div>
            <p class="product-single__price product-single__price-product-template">
                <span class="visually-hidden">Regular price</span>
                <s id="ComparePrice-product-template"><span class="money">@Model.Price1</span></s>
                <span class="product-price__price product-price__price-product-template product-price__sale product-price__sale--single">
                    <span id="ProductPrice-product-template"><span class="money">@Model.Price1</span></span>
                </span>
            </p>
            <div class="product-single__description rte">
                @Model.MetaDescription
            </div>

            <div id="product_form_10508262282"  class="product-form product-form-product-template hidedropdown">

                <!-- Product Action -->
                <div class="product-action clearfix">
                   @* <div class="product-form__item--quantity">
                        <div class="wrapQtyBtn">
                            <div class="qtyField">
                                <a class="qtyBtn minus" href="javascript:void(0);"><i class="fa anm anm-minus-r" aria-hidden="true"></i></a>
                                <input type="text" id="Quantity" name="quantity" value="1" class="product-form__input qty">
                                <a class="qtyBtn plus" href="javascript:void(0);"><i class="fa anm anm-plus-r" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>*@
                    <div class="product-form__item--submit">
                        <form  asp-controller="Cart" asp-action="Post" method="post">
                            <input asp-for="@Model.Id" class="form-control" type="text" hidden />
                            <button class="btn btn-addto-cart" type="submit" title="">Add Cart</button>
                        </form>
                    </div>
                </div>
                <!-- End Product Action -->
            </div>

        </div>
    </div>
</div>

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Views/Home/Posts.cshtml
@model List<ProductViewModel>
@{
    ViewData["Title"] = "Posts";
}

@foreach (ProductViewModel item in Model)
{
    <div class="col-6 col-sm-6 col-md-4 col-lg-3 item">
        <!-- start product image -->
        <div class="product-image">
            <!-- start product image -->
            <a asp-controller="Home" asp-action="Post" asp-route-id="@item.Id">
                <!-- image -->
                <img class="primary blur-up ls-is-cached lazyloaded" data-src="@item.Barcode" src="@item.Barcode" alt="image" title="product">
                <!-- End image -->

            </a>
            <!-- end product image -->
            <!-- Start product button -->
            <form class="variants add" asp-controller="Cart" asp-action="Post" method="post">
                <input asp-for="@item.Id" class="form-control" type="text" hidden />
                <button class="btn btn-addto-cart" type="submit" title="">Add Cart</button>
            </form>

            <!-- end product button -->
        </div>
        <!-- end product image -->
        <!--start product details -->
        <div class="product-details text-center">
            <!-- product name -->
            <div class="product-name">
                <a href="@item.FullName">@item.FullName</a>
            </div>
            <!-- End product name -->
            <!-- product price -->
            <div class="product-price">
                <h3>@item.Price1</h3>
            </div>
            <!-- End product price -->
            <!-- Variant -->
            <!-- End Variant -->
        </div>
        <!-- End product details -->

    </div>

}