Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Areas/Admin/Models/ProductImageViewModels/ProductImageViewModel.cs
using MKaymaz_ECommerce.Common.Enums;
using MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.ProductViewModels;
using System;

namespace MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.ProductImageViewModels
{
    public class ProductImageViewModel
    {
        public Guid Id { get; set; }
        public Status Status { get; set; }

        public string Filename { get; set; }
        public string Extension { get; set; }
        public string DirectoryName { get; set; }
        public string Revision { get; set; }
        public int? SortOrder { get; set; }
        public string Attachment { get; set; }

        public Guid ProductId { get; set; }
        public ProductViewModel Product { get; set; }
    }
}

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Areas/Admin/Controllers/ProductImageController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MKaymaz_ECommerce.Common.Dtos.ProductImage;
using MKaymaz_ECommerce.Web.UI.APIs;
using MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.ProductImageViewModels;
using MKaymaz_ECommerce.Web.UI.Areas.Admin.Models.ProductViewModels;
using MKaymaz_ECommerce.Web.UI.Infrastructure.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MKaymaz_ECommerce.Web.UI.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
    public class ProductImageController : Controller
    {
        private readonly IProductImageApi _productImageApi;
        private readonly IProductApi _productApi;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _env;

        public ProductImageController(
            IProductImageApi productImageApi,
            IMapper mapper,
           IWebHostEnvironment env, IProductApi productApi)
        {
            _productImageApi = productImageApi;
            _mapper = mapper;
            _env=env;
            _productApi=productApi;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (User.Claims.FirstOrDefault(x => x.Type == "IsAdmin")?.Value != "True")
                return Redirect("/Home/Index");
            List<ProductImageViewModel> list = new List<ProductImageViewModel>();
            var listResult = await _productImageApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductImageViewModel>>(listResult.Content.ResultData);
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> Insert()
        {
            List<ProductViewModel> list = new List<ProductViewModel>();
            var listResult = await _productApi.List();
            if (listResult.IsSuccessStatusCode &&
                listResult.Content.IsSuccess &&
                listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductViewModel>>(listResult.Content.ResultData);
            ViewBag.Products = new SelectList(list, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Insert(CreateProductImageViewModel item, List<IFormFile> files)
        {
            if (User.Claims.FirstOrDefault(x => x.Type == "IsAdmin")?.Value != "True")
                return Redirect("/Home/Index");
            if (ModelState.IsValid)
            {
                bool imageResult;
                string imagePath = Upload.ImageUpload(files, _env, out imageResult);
                if (imageResult)
                    item.Attachment = imagePath;
                else
                {
                    TempData["Message"] = imagePath;
                    return View(item);
                }

                var insertResult = await _productImageApi.Post(_mapper.Map<ProductImageRequestDto>(item));
                if (insertResult.IsSuccessStatusCode &&
                    insertResult.Content.IsSuccess &&
                    insertResult?.Content?.ResultData != null)
                    return RedirectToAction("Index");
                else
                    TempData["Message"] = "Kayıt işlemi sırasında bir hata oluştu!... Lütfen alanları kontrol edip tekrar deneyinzi...";
            }
            TempData["Message"] = "İşlem başarısız oldu!... Lütfen alanları kontrol edip tekrar deneyinzi...";

            List<ProductViewModel> list = new List<ProductViewModel>();
            var listResult = await _productApi.List();
            if (listResult.IsSuccessStatusCode &&
                listResult.Content.IsSuccess &&
                listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductViewModel>>(listResult.Content.ResultData);
            ViewBag.Products = new SelectList(list, "Id", "Name");


            return View(item);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            if (User.Claims.FirstOrDefault(x => x.Type == "IsAdmin")?.Value != "True")
                return Redirect("/Home/Index");
            List<ProductViewModel> list = new List<ProductViewModel>();
            var listResult = await _productApi.List();
            if (listResult.IsSuccessStatusCode &&
                listResult.Content.IsSuccess &&
                listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductViewModel>>(listResult.Content.ResultData);
            ViewBag.Products = new SelectList(list, "Id", "Name");


            UpdateProductImageViewModel model = new UpdateProductImageViewModel();
            var updateResult = await _productImageApi.Get(id);
            if (updateResult.IsSuccessStatusCode && updateResult.Content.IsSuccess && updateResult.Content.ResultData != null)
                model = _mapper.Map<UpdateProductImageViewModel>(updateResult.Content.ResultData);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateProductImageViewModel item)
        {
            if (ModelState.IsValid)
            {
                var updateResult = await _productImageApi.Put(item.Id, _mapper.Map<ProductImageRequestDto>(item));
                if (updateResult.IsSuccessStatusCode &&
                    updateResult.Content.IsSuccess &&
                    updateResult?.Content?.ResultData != null)
                    return RedirectToAction("Index");
                else
                    TempData["Message"] = "Güncelleme sırasında bir hata oluştu!... Lütfen alanları kontrol edip tekrar deneyinzi...";
            }
            TempData["Message"] = "İşlem başarısız oldu!... Lütfen alanları kontrol edip tekrar deneyinzi...";
            return View(item);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var deleteResult = await _productImageApi.Delete(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Activate(Guid id)
        {
            var activateResult = await _productImageApi.Activate(id);
            return RedirectToAction("Index");
        }
    }
}

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Areas/Admin/Views/ProductImage/Index.cshtml
@model List<ProductImageViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<!-- Main Content -->
<div class="body_scroll">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Product Image </h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">Product Images</li>
                    <li class="breadcrumb-item active">Product Image list</li>
                </ul>
                <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button"><i class="zmdi zmdi-arrow-right"></i></button>
                <a asp-controller="ProductImage" asp-action="Insert" class="btn btn-success btn-icon float-right"><i class="zmdi zmdi-plus"></i></a>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="card project_list">
                    <div class="table-responsive">
                        <table class="table table-hover c_table">
                            <thead>
                                <tr>
                                    <th>Product Name</th>
                                    <th>Sort Order</th>
                                    <th>Status</th>
                                    <th><span class="badge badge-info">Activate Button</span></th>
                                    <th><span class="badge badge-warning">Update Button</span></th>
                                    <th><span class="badge badge-danger">Delete Button</span></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (ProductImageViewModel item in Model)
                                {
                                    <tr>
                                        <td>@item.Filename</td>
                                        <td>@item.SortOrder</td>
                                        <td><partial name="PartialViews/_StatusPartial" model="item.Status" /></td>
                                        <td>
                                            <a asp-controller="ProductImage" asp-action="Activate" asp-route-id="@item.Id" class="badge badge-info"><span>Activate</span></a>
                                        </td>
                                        <td>
                                            <a asp-controller="ProductImage" asp-action="Update" asp-route-id="@item.Id" class="badge badge-warning"><span>Update</span></a>
                                        </td>
                                        <td>
                                            <a asp-controller="ProductImage" asp-action="Delete" asp-route-id="@item.Id" class="badge badge-danger"><span>Delete</span></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <ul class="pagination pagination-primary mt-4">
                        <li class="page-item active"><a class="page-link" href="javascript:void(0);">1</a></li>
                        <li class="page-item"><a class="page-link" href="javascript:void(0);">2</a></li>
                        <li class="page-item"><a class="page-link" href="javascript:void(0);">3</a></li>
                        <li class="page-item"><a class="page-link" href="javascript:void(0);">4</a></li>
                        <li class="page-item"><a class="page-link" href="javascript:void(0);">5</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Areas/Admin/Views/ProductImage/Insert.cshtml
@model CreateProductImageViewModel
@{
    ViewData["Title"] = "Insert";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="body_scroll">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Add ProductImage</h2>
                <ul class="breadcrumb">
                     <li class="breadcrumb-item"><a asp-controller="ProductImage" asp-action="Index" asp-area"">ProductImage</a></li>
                </ul>
                <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button"><i class="zmdi zmdi-arrow-right"></i></button>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <form asp-controller="ProductImage" asp-action="Insert" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="body">
                            <div class="form-group">
                                <input asp-for="Filename" type="text" class="form-control" placeholder="File Name" />
                            </div>
                            <br />
                            <div class="form-group">
                                <input asp-for="Extension" type="text" class="form-control" placeholder="Extension" />
                            </div>
                            <br />
                            <div class="form-group">
                                <input asp-for="DirectoryName" type="text" class="form-control" placeholder="Directory Name" />
                            </div>
                            <div class="form-group">
                                <select asp-for="ProductId" asp-items="@ViewBag.Products" class="form-control">
                                    <option>Please select Product..</option>
                                </select>
                            </div>
                             <div class="form-group">
                                <input class="form-control" type="file" name="files">
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="body">
                            <button type="submit" class="btn btn-info waves-effect m-t-20">SAVE</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["Message"]
        </div>
    }
</div>

Final Projesi/MKaymaz_ECommerce/Presentation/MKaymaz_ECommerce.Web.UI/Areas/Admin/Views/ProductImage/Update.cshtml
@model UpdateProductImageViewModel
@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="body_scroll">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Update Product Image</h2>
                <ul class="breadcrumb">
                     <li class="breadcrumb-item"><a asp-controller="ProductImage" asp-action="Index" asp-area"">ProductImage</a></li>
                </ul>
                <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button"><i class="zmdi zmdi-arrow-right"></i></button>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <form asp-controller="ProductImage" asp-action="Update" method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="Id" />
                    <div class="card">
                        <div class="body">
                            <div class="form-group">
                                <input asp-for="Filename" type="text" class="form-control" placeholder="File Name" />
                            </div>
                            <br />
                            <div class="form-group">
                                <input asp-for="Extension" type="text" class="form-control" placeholder="Extension" />
                            </div>
                            <br />
                            <div class="form-group">
                                <input asp-for="DirectoryName" type="text" class="form-control" placeholder="Directory Name" />
                            </div>
                            <div class="form-group">
                                <select asp-for="ProductId" asp-items="@ViewBag.Products" class="form-control">
                                    <option>Please select Product..</option>
                                </select>
                            </div>
                             <div class="form-group">
                                <input class="form-control" type="file" name="files">
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="body">
                            <button type="submit" class="btn btn-info waves-effect m-t-20">UPDATE</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["Message"]
        </div>
    }
</div>